server {
  listen 3000;
  server_name localhost;
  root /usr/share/nginx/html;
  index index.html index.htm;
  absolute_redirect off;
  port_in_redirect off;

  location / {
    try_files $uri $uri/index.html /index.html;
  }
}
